<?php
$napis = "NaPiS dO tEsToW";
echo "napis: $napis <br>";
echo "dlugosc: ";
echo strlen($napis);
echo "<br>";
echo "ilosc slow: ";
echo str_word_count($napis);
echo "<br>";
echo "Od tylu: ";
echo strrev($napis);
echo "<br>";
echo 'Znajdz pozycje "do" ';
echo strpos($napis, "dO");
echo "<br>";
echo 'Zmien wyraz: ';
echo str_replace("dO","nA",$napis);
echo "<br>";
echo 'Zmien litery: ';
echo strtr($napis,"O","0");
echo "<br>";
echo 'Odciecie: ';
echo trim($napis,"tEsToW");
echo "<br>";
echo 'Wyszukaj: ';
echo strrchr($napis,"dO");
echo "<br>";
echo 'Do malych: ';
echo strtolower($napis);
echo "<br>";
echo 'Do duzych: ';
echo strtoupper($napis);
echo "<br>";
echo 'Wycinanie: ';
echo substr($napis,3,7);
echo "&nbsp&nbsp&nbsp&nbsp&nbsp";
echo substr($napis,2,9);
echo "&nbsp&nbsp&nbsp&nbsp&nbsp";
echo substr($napis,1,5);
echo "&nbsp&nbsp&nbsp&nbsp&nbsp";
?>
